<?php
/**
 * ContractorsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Manage Contractors APIs
 *
 * This API supports all services required to manage Employees on HR system
 *
 * OpenAPI spec version: 0.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 1.0.16
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ContractorsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContractorsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for contractorsEmployeeIDDelete
     *
     * Deletes an Employee record.
     *
     */
    public function testContractorsEmployeeIDDelete()
    {
    }

    /**
     * Test case for contractorsEmployeeIDGet
     *
     * Retrieves an Employee record.
     *
     */
    public function testContractorsEmployeeIDGet()
    {
    }

    /**
     * Test case for contractorsGet
     *
     * Retrieves all Employee records.
     *
     */
    public function testContractorsGet()
    {
    }

    /**
     * Test case for contractorsPost
     *
     * Creates an Employees.
     *
     */
    public function testContractorsPost()
    {
    }
}
